version: '3.8'

services:
  app:
    image: 192497948979.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest
    container_name: nodejs-app
    restart: always
    ports:
      - "9000:9000"
    environment:
      DB_HOST: 10.0.1.41
      DB_USER: root
      DB_PASSWORD: new_password
      DB_NAME: loginDB
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
